- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
  tasks:
    - name: debug username
      debug:
        msg: path is /home/{{ username }}/
    - name: Update apt cache
      become: true
      apt: update_cache=yes
    - name: install packages
      apt:
        pkg:
          - zsh
          - tmux
          - powerline
    - name: copy .zsh settings
      copy:
        src: .zshrc
        dest: /home/{{ username }}/.zshrc
    - name: oh my zsh install
      shell: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
