- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
  tasks:
    - name: debug username
      debug:
        msg: path is "{{ ansible_env.HOME }}" 
    - name: Update apt cache
      become: true
      apt: update_cache=yes
    - name: install packages
      become: true
      apt:
        pkg:
          - zsh
          - tmux
          - powerline
    - name: rm ohmyzsh if it is
      shell: 'rm -fr {{ ansible_env.HOME}}/.oh-my-zsh'
    - name: oh my zsh install
      shell: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
    - name: install autosuggestions
      shell: 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions'


    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ username }}"
        shell: /bin/zsh        
    - name: install syntax
      shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  
    - name: copy .zsh  and .tmux settings
      template:
        src: "{{ item.src }}"
        dest: "/{{ ansible_env.HOME }}"
      with_items:
        - { src: .zshrc }
        - { src: .tmux.conf }
    - name: copy theme
      copy:
        src: agnoster.zsh-theme
        dest: "{{ansible_env.HOME}}/.oh-my-zsh/themes"
