- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
  tasks:
    - name: debug username
      debug:
        msg: path is /home/{{ username }}/
    - name: Update apt cache
      become: true
      apt: update_cache=yes
    - name: install packages
      apt:
        pkg:
          - zsh
          - tmux
          - powerline
    - name: rm ohmyzsh if it is
      shell: 'rm -fr /home/{{ username }}/.oh-my-zsh'
    - name: oh my zsh install
      shell: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
    - name: install autosuggestions
      shell: 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions'
    - name: copy .zsh  and .tmux settings
      template:
        src: "{{ item.src }}"
        dest: /home/{{ username }}/
      with_items:
        - { src: .zshrc }
        - { src: .tmux.conf }
    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ username }}"
        shell: /bin/zsh        
